import os

# Load config
configfile: "config/config.yaml"
config["threads"] = workflow.cores

fasta = config["file_path"]
db_dir = config["database_dir"]
output_dir = config["output_dir"]
filename = config["filename"]


# Load modules from config
included_modules = config.get("include_modules", [])
for rule_path in included_modules:
    include: rule_path

# Dynamically build list of expected outputs
all_outputs = []

# Module 1
if "workflow/rules/module_1/recognizer.smk" in included_modules:
    all_outputs.append(f"{output_dir}/recognizer_results/reCOGnizer_results.tsv")

if "workflow/rules/module_1/eggnogmapper.smk" in included_modules:
    all_outputs.append(f"{output_dir}/eggnogmapper_results/eggnog_mapper_results.emapper.annotations")

if "workflow/rules/module_1/upimapi.smk" in included_modules:
    all_outputs.append(f"{output_dir}/upimapi/UPIMAPI_results.tsv")

# Module 2
if "workflow/rules/module_2/colabfold.smk" in included_modules:
    all_outputs.append(f"{output_dir}/colabfold/config.json")

if "workflow/rules/module_2/deepfri.smk" in included_modules:
    all_outputs.append("data/deepfri_src/.requirements_done")
    all_outputs.append(f"{output_dir}/deepfri/DeepFRI_MF_predictions.csv")

if "workflow/rules/module_2/foldseek.smk" in included_modules:
    all_outputs.append(f"{output_dir}/foldseek/output_easy_search.m8")
    all_outputs.append("data/databases/foldseek_db/.pdb_ready")

# Module 3
if "workflow/rules/module_3/clean.smk" in included_modules:
    all_outputs.append(f"{output_dir}/clean/{filename}_maxsep.csv")

if "workflow/rules/module_3/deepgo_se.smk" in included_modules:
    all_outputs.append("data/deepgo2/predict.py")
    all_outputs.append(f"{output_dir}/deepgo2/{filename}_preds_mf.tsv")

# Final rule
rule all:
    input:
        all_outputs
